name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run end to end test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Compile action
        run: npm run dist
      - name: Run local file-diff action
        uses: ./
        with:
          lhs: './fixtures/example_1.txt'
          rhs: './fixtures/example_2.txt'
          fail: 'true'
          debug: 'true'
          compare: 'true'
      - name: Run local file-diff action
        uses: ./
        with:
          lhs: './fixtures/example_1.txt'
          rhs: './fixtures/example_3.txt'
          fail: 'false'
          debug: 'true'
          compare: 'true'

